class User < ApplicationRecord
  has_many :listings
  has_many :comments
  belongs_to :cart, optional: true
<<<<<<< HEAD
  # has_secure_password
  #   ###need to create migrations for has_secure_password
  #
=======
  validates :username, uniqueness: true
    ###need to create migrations for has_secure_password

>>>>>>> 79c23ba6f0e786852e4d247ae0b4a1bc0ed0c197
  # def password=(new_password)
  #   salt = BCrypt::Engine::generate_salt
  #   hashed = BCrypt::Engine::hash_secret(new_password, salt)
  #   self.password_digest = salt + hashed
  # end
<<<<<<< HEAD
  #
  # # authenticate(password: string) -> User?
=======

  # authenticate(password: string) -> User?
>>>>>>> 79c23ba6f0e786852e4d247ae0b4a1bc0ed0c197
  # def authenticate(password)
  #   # Salts generated by generate_salt are always 29 chars long.
  #   salt = password_digest[0..28]
  #   hashed = BCrypt::Engine::hash_secret(password, salt)
  #   return nil unless (salt + hashed) == self.password_digest
  # end
end
